version: '3.8'

services:

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: unlimitd
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Europe/Paris"
    ports:
      - "5432:5432"
    volumes:
      - db_unlimitd:/var/lib/postgresql/data/
    restart: always


volumes:
  db_unlimitd:
